apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/catalogue
        imagePullPolicy: Always
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 80
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 2
          periodSeconds: 10
            name: catalogue
        resources:
          requests:
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: frontend
    component: catalogue
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    tier: frontend
    component: catalogue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

