apiVersion: v1
kind: ConfigMap
metadata: 
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_pass: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/rabbitmq
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: rabbitmq
      resources:
        requests:
          cpu: "128m"
          memory: "256Mi"
        limits:
          cpu: "256m"
          memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672