apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/mongodb
        imagePullPolicy: Always
      resources:
        requests:
          cpu: "128m"
          memory: "256Mi"
        limits:
          cpu: "256m"
          memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mongodb
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017     