apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      containers:
      - name: mysql
        image: 966392474288.dkr.ecr.us-east-1.amazonaws.com/mysql
        imagePullPolicy: Always
      resources:
        requests:
          cpu: "256mm"
          memory: "512MiMi"
        limits:
          cpu: "400m"
          memory: "756Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  type: ClusterIP
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306